export type Severity = 'log' | 'warn' | 'error' | 'debug'

export interface Entry {
  /**
   * A random ID generated by nibbana
   * 
   * @type {string}
   * @memberof Entry
   */
  _id: string
  severity: Severity
  occurredAt: Date

  /**
   * The super properties registered with your nibbana instance
   * 
   * @type {object}
   * @memberof Entry
   */
  superProperties: object

  /**
   * The data contained in this entry
   * 
   * @type {any[]}
   * @memberof Entry
   */
  data: any[]
}
