export interface IAsyncStorage {
  getItem(key: string, callback?: (error?: Error, result?: string) => void): Promise<string>
  setItem(key: string, value: string, callback?: (error?: Error) => void): Promise<void>
  removeItem(key: string, callback?: (error?: Error) => void): Promise<void>
}

export type Severity = 'log' | 'warn' | 'error'

export interface Entry {
  /**
   * A random ID generated by nibbana
   * 
   * @type {string}
   * @memberof Entry
   */
  _id: string
  severity: Severity
  occurredAt: Date

  /**
   * The main content of your log entry
   * 
   * @type {string}
   * @memberof Entry
   */
  message: string

  /**
   * If you log an Error object, this will be set to error.name
   * 
   * @type {string}
   * @memberof Entry
   */
  errorName?: string

  /**
   * If you log an Error object and it comes with a stack trace, this will be set to error.stack
   * 
   * @type {string}
   * @memberof Entry
   */
  stack?: string

  /**
   * The super properties registered with your nibbana instance
   * 
   * @type {object}
   * @memberof Entry
   */
  superProperties: object
}

export type UploadEntriesFunction = (entries: Entry[]) => Promise<any>

export interface NibbanaConfig {
  /**
   * Whether besides uploading entries, we should also write to the console.
   */
  outputToConsole: boolean

  /**
   * The url at which nibbana-server is reachable.
   * 
   * @type {string}
   * @memberof NibbanaConfig
   */
  endpoint: string

  /**
   * Must be the same as on the server or your uploads will fail.
   * 
   * @type {string}
   * @memberof NibbanaConfig
   */
  secretToken: string

  /**
   * If this is set to a value greater than 0, our local entries store is turned into a bounded queue that discards old entries once we reach our capacity. Be careful with this setting.
   * 
   * @type {number}
   * @memberof NibbanaConfig
   */
  capacity: number

  /**
   * If you leave this.uploadEntries set to its default value, these http headers will be added to your request.
   * 
   * @memberof NibbanaConfig
   */
  additionalHTTPHeaders: () => any

  /**
   * Use this when you want to provide your own uploading logic. Make sure your requests time out after a reasonable amount of time.
   * 
   * @memberof NibbanaConfig
   */
  uploadEntries: UploadEntriesFunction

  /**
   * Used for testing. You should probably not fiddle with this.
   * 
   * @type {IAsyncStorage}
   * @memberof NibbanaConfig
   */
  asyncStorage: IAsyncStorage
}
